version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app  
  test: # Using this solution, we are not going to be able to pass commands to our test suite.
  #Using docker attach, we get a handle on npm start, not the test command. So the inputs dont work
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app  
    command: ["npm", "run", "test"]  